### ISSUE TITLE
allennlp Prediction parameter

### ISSUE THREAD

**Issue by ishay2b** [benbogin/spider-schema-gnn#1]
Hi @benbogin , 
I was able to complete successful training and reproduce your benchmarks. Thanks for the excellent code and article.

While trying to predict using trained net with this command:

`allennlp predict \
--include-package dataset_readers.spider \
--include-package models.semantic_parsing.spider_parser \
--output-file simple_test_output.json \
--cuda-device 0 \
--weights-file experiments/name_of_experiment/best.th \
experiments/name_of_experiment/model.tar.gz \
experiments/name_of_experiment/simple_test_input.json
`

I Received this error:
`allennlp.common.checks.ConfigurationError: 'No default predictor for model type spider.\nPlease specify a predictor explicitly.'`

Can you please advice with a simple example predicting even on the train/dev/val spider set?

**Comment by benbogin** [comment]
Thanks for the feedback!
I've updated the code and readme file to support the predict command. Let me know if there's any trouble.

**Comment by ishay2b** [comment]
Works great. 

BTW, You are missing predictions/__init__.py file. 
And also nltk download, as can be seen in my fork.
