### ISSUE TITLE
Adding my own database_issue

### ISSUE THREAD

**Issue by abhisun** [benbogin/spider-schema-gnn#10]
Hello,
I created my own database directory and added my schema.sql and <database_name>.sqlite file. 
I added the values to tables.json as well.

But, when I am running the allennlp predict command
- I had trouble initially with 'is_global_variable = True' for table name. It turned out that my table name is being read as " 'mock' " instead of "mock". 
- I tried checking the names in the schema, tables.json and .sqlite file. I am not able to pinpoint the issue.
- I made a small correction to the validation for "is_global_item" to account for single quotes and moved on.
- But, now, I have issues with entities and entity_maps.
 **_File "./models/semantic_parsing/spider_parser.py", line 592, in <listcomp>
    entity_ids = [entity_map[entity] for entity in entities]
KeyError: "'mock'"_**

Please let me know if this is a known error and if there is a workaround.

**Comment by benbogin** [comment]
Hi!
Is there by any chance only one table in the dataset? There is a problem in the way the grammar package handles rules (`semparse/contexts/spider_db_grammar.py`) where there is only one value in the right hand side. Is this your case?

**Comment by abhisun** [comment]
Hi Ben,

Yes, I have only one table in the database. The validations like "is_global_rule" and adding to "valid_actions" and "is_nonterminal" etc make checks for double quotes (""). I temporarily added checks for single quotes as well. This took care of the issues. I will have to check it with other spider dataset to see if it breaks something else.

Best,
Abhi

**Comment by benbogin** [comment]
Thanks Abhi.
Please let me know if you find other issues with this fix.

**Comment by papsipublic** [comment]
Hi,

I would kindly ask for help for generating the ".sqlite" file for  a new database/table.

For my own data, i create the directory "mytable", under which I put the schema.sql file and use ".rad" to open and interrogate it in sqlite. It works fine.

But I do not know how to generate the ".sqlite" file file, like "mutable.sqlite".

I appreciate any piece of advice.

thank you
