### ISSUE TITLE
Unexpected outputs from custom data

### ISSUE THREAD

**Issue by abhisun** [benbogin/spider-schema-gnn#11]
Hi,
I used some custom data and my own statements to check the performance. Below are some of the predicted outputs. And most of them do not make sense.

select count ( * ) from 'mock'
select count ( * ) from 'mock' where ' value '
select * from 'mock' where count ( * ) > ' value '
select count ( * ) from 'mock' group by count ( * ) having ' value '
select count ( * ) , count ( * ) from 'mock' group by count ( * ) having ' value '
NO PREDICTION
NO PREDICTION
NO PREDICTION
select count ( * ) from 'mock' group by count ( * ) having count ( * ) > ' value '
NO PREDICTION
select * from 'mock' where count ( * ) > ' value '
select count ( * ) from 'mock' group by count ( * ) having count ( * ) > ' value '
NO PREDICTION
select count ( * ) , mock.gender from ( select count ( * ) from 'mock' where count ( * ) = ( select count ( * ) from 'mock' ) ) group by count ( * )

Not being accurate is one thing but getting grammatically incorrect tokens in SQL was unexpected. Do you think while decoding the SQL grammar is not being applied properly (some issues with my pipeline) or while encoding the schema tokens are not being applied to the embedding vectors. Any help is much appreciated.

Thanks & Regards,
Abhi

**Comment by benbogin** [comment]
Hi Abhi,
The grammar rules of the model restrict it to output queries that are mostly valid, however this restriction is not 100% accurate - this will be quite hard to achieve, and not too necessary since the model will usually learn to output valid queries. 

In your case, I'm not sure which invalid queries you're referring to, but in any case, it seems like training didn't go too well - did you have enough training data and training time?

**Comment by abhisun** [comment]
Hi Ben,

Thanks for the response. I used the model trained on spider dataset to check the prediction on new unseen data. I thought this would work on databases not yet seen by the model. 
My issues - "Count(*)" is being applied everywhere like after "group by" and "having". 
Do you think I should train on my data to have any predictions?

**Comment by benbogin** [comment]
Did your model get ~41-42% accuracy on the spider dataset?

**Comment by abhisun** [comment]
Yes, and it predicts the validation statements from Spider perfectly. Only when I use my own database and questions it gets very bumpy. I am checking the entire pipeline if the columns are being recognized well. I will keep you updated. We can close the issue if you would like I just wanted your attention to ask you about the problem.

**Comment by benbogin** [comment]
Since no columns were decoded in any sample you provided, perhaps it's indeed a matter of configuring the schema. The model should usually give reasonable predictions on unseen schemas. Let me know if there's any further issue you'd like to discuss.
