### ISSUE TITLE
How to run prediction without provide `query_toks_no_value` into the test data ?

### ISSUE THREAD

**Issue by hailq** [benbogin/spider-schema-gnn#14]
I tried to remove `query_toks_no_value` from the spider test data to run the predict but it's crashed. It makes no sense to include that field when running the prediction :S

``` 

  File "/venv/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 76, in read
    "Is the path correct?".format(file_path))
allennlp.common.checks.ConfigurationError: 'No instances were read from the given filepath /spider-schema-gnn/test/dev.json. Is the path correct?'
```

**Comment by benbogin** [comment]
Right, the issue is that during inference allennlp takes the training dataset reader setting and not the validation settings (this was fixed in later allennlp versions). I have committed a small fix - also take a look at the updated predict command in the readme. Let me know if there are any issues

**Comment by hailq** [comment]
please reopen it, i get this issue when set `keep_if_unparsable` is `True`:
```
spider_evaluation/process_sql.py", line 511, in parse_sql
    if toks[idx] == '(':
IndexError: list index out of range
```

**Comment by benbogin** [comment]
After updating to the latest commit?
Can you send the error full stack trace?

**Comment by hailq** [comment]
It works with the latest commit 👍
