### ISSUE TITLE
How to predict for a single question

### ISSUE THREAD

**Issue by sravand93** [benbogin/spider-schema-gnn#15]
Hi ,

It seems that through the allennlp predict command, it is accepting a test file only  in .json format. so is there any way  to provide a single question text as an argument and predict the sql query for that single question. 

Thank You

**Comment by benbogin** [comment]
Hi,
You could either have a json file with one single question, or use the [allennlp server](https://allenai.github.io/allennlp-docs/api/allennlp.service.server_simple.html) to do this interactively.
