### ISSUE TITLE
predicting 'value' in where and having clauses instead of the actual entity value

### ISSUE THREAD

**Issue by sravand93** [benbogin/spider-schema-gnn#16]
Hi 
when I am trying to predict sql queries for different questions, the model is generating a query and when the query involves a where or having clause, it is generating 'value' text in the predicate instead of the original entity value. 
eg: 
question: "What is the email id for the person with first name as 'asp'"
predicted : select leads.email from leads where leads.firstname = ' value '
expected : select leads.email from leads where leads.firstname = ' asp'

I am also able to see the similar queries  for the examples you mentioned in the paper and I didn't find any information regarding this in the paper. Is it some thing that is expected with this model? what is the reason for this and is there any other way to get the entity value instead of "value" text. 

Your response is much appreciated. Thank you

**Comment by benbogin** [comment]
Hi,
This is indeed the way that the model works, as this is the way that results are being evaluated in the spider dataset.
Currently the model doesn't support prediction of values, but it could be trained to do so with some modifications - mostly, adding grammar rules for each one of the words in the sentence and deciding how the decoder selects these.
