### ISSUE TITLE
For real industrial application, what strategy to locate the exact table?

### ISSUE THREAD

**Issue by guotong1988** [benbogin/spider-schema-gnn#18]
The datasets is that the table corresponding to question is given.

But in real industrial application, we have 100+ tables for 1 new question.

Thank you!

**Comment by benbogin** [comment]
Hi!
The entity linker in the model looks for alignment between parts of questions and names of tables, so in theory it could work with any number of tables. Practically, it works well for spider but real-case uses will need to adapt the entity-linker to be more suitable to the problem at hand.
