### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by hailq** [benbogin/spider-schema-gnn#19]
I ran on 1 gpu with batch_size=13 and got cuda memory issue. It works if I reduce batch_size but your default batch_size is 15, how did you train, did you setup multiple gpus - how to do that?

**Comment by benbogin** [comment]
Hey, I ran experiments with gpus that had 11 or 12 GB, which were enough for the batch size. You will probably need to reduce the batch size to fit everything, or use multiple gpus - I did not that do so do not have any code available for that.
