### ISSUE TITLE
creating the ".sqlite" feel for new data

### ISSUE THREAD

**Issue by papsipublic** [benbogin/spider-schema-gnn#23]
Hi,

I would kindly ask for help for generating the ".sqlite" file for a new database/table.

For my own data, i create the directory "mytable", under which I put the schema.sql file and use ".rad" to open and interrogate it in sqlite. It works fine.

But I do not know how to generate the ".sqlite" file file, like "mutable.sqlite".

I appreciate any piece of advice.

thank you

**Comment by benbogin** [comment]
Hi,
we didn't create the `sqlite` files, we got them from [spider dataset](https://github.com/taoyds/spider).
I would assume you need a sqlite software/tool to create this file.
