### ISSUE TITLE
[Question] Training Time

### ISSUE THREAD

**Issue by beneyal** [benbogin/spider-schema-gnn#8]
Hi Ben,

How long did it take you to train the model, and on what GPU? I ran training on a K80 and it took ~13 hours and 55 epochs until convergence, and was wondering if you experienced the same.

Thanks,
Ben

**Comment by benbogin** [comment]
Hi Ben, that's pretty much the same training time as I've experienced.
Note that there are probably many places where the model could be speed-optimized - I have not explored that too much.

**Comment by beneyal** [comment]
Awesome, thanks!
