### ISSUE TITLE
Prediction without validation

### ISSUE THREAD

**Issue by abhisun** [benbogin/spider-schema-gnn#9]
Hi,
I am just trying to predict sql queries for english statements. I am using the same command as mentioned for "Inference". In my input .json file, I removed all the tokens except for "db_id" and "question".

At first I had to change load_cache = False to run the program. 

Then the "spider.text_to_instance" function  had some issues. It was returning a None for instance. It was expecting a sql query as one of the parameters. - I put sql = [] to make it return a non-Null instance. But, I think action_sequence is now empty.

Can you please give me a brief explanation on what changes to make to just predict without any evaluation and what exactly are spiderworld and action_sequence doing?
Thank you!
Best regards,
Abhi

**Comment by henryyang42** [comment]
I had the same problem before. I made [this change](https://github.com/henryyang42/spider-schema-gnn/commit/510bbdeb9a83349c762c906fc0a39f14676e5bbc) so that I can run on custom queries.

**Comment by benbogin** [comment]
Hi Abhi!
I saw there was a comment here (can't see it now - maybe it was deleted?) with a possible solution: https://github.com/henryyang42/spider-schema-gnn/commit/510bbdeb9a83349c762c906fc0a39f14676e5bbc

Does this solve your problem?

The text_to_instance shouldn't really need the sql parameter, but because of some AllenNLP issue (I'm pretty sure this is fixed in a version update) it cannot be passed NULL. Perhaps as a temporary fix to see if this is the issue, you can pass there some valid sql statement?

**Comment by henryyang42** [comment]
```python
from dataset_readers.spider import SpiderDatasetReader
from models.semantic_parsing.spider_parser import SpiderParser
from predictors.spider_predictor import WikiTablesParserPredictor


dataset_reader = SpiderDatasetReader(load_cache=False, save_cache=False,
                                     tables_file=os.path.join(settings.SPIDER_DATASET, 'tables.json'))
archive = load_archive(settings.SPIDER_SCHEMA_GNN_MODEL)
predictor = Predictor.from_archive(archive, 'spider')

def nl2sql(db_id, question):
    """Generate SQL given `db_id` and NL `question`.

    Arguments:
        db_id {str} -- DB id in Spider corpus
        question {str} -- NL question
    """
    instance = dataset_reader.text_to_instance(
        utterance=question,
        db_id=db_id)
    result = predictor.predict_instance(instance)
    return result
```
Thanks, the problem was solved. I used the above code snippet.

**Comment by benbogin** [comment]
Great!

**Comment by abhisun** [comment]
Hi Ben/Harry,

Thanks for responding. I made a temporary fix to pass empty sql (sql=[]). It seems to work for now but I will also look at the above snippet.

Thanks.
